# Generated by Django 5.2.3 on 2025-06-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
    ]
