# Generated by Django 5.2.3 on 2025-06-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_assignment_rubric_rubriccriterion_submission_and_more"),
        ("users", "0003_remove_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="academics.department",
            ),
        ),
    ]
