# Generated by Django 5.2.3 on 2025-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0018_alter_academicyear_options_alter_assessment_options_and_more",
        ),
        ("users", "0004_userprofile_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assigned_courses",
            field=models.ManyToManyField(
                blank=True,
                help_text="The course(s)/program(s) this staff member is assigned to.",
                related_name="staff_profiles",
                to="academics.course",
            ),
        ),
    ]
