# Generated by Django 5.2.3 on 2025-07-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0020_remove_courseplan_subject_remove_assignment_subject_and_more",
        ),
        ("users", "0005_remove_userprofile_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="assigned_courses",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="academics.department",
            ),
        ),
    ]
