# Generated by Django 5.2.3 on 2025-06-25 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(unique=True)),
                ("end_date", models.DateField(unique=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Midterm Exam, Assignment, Project, Quiz",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Type",
                "verbose_name_plural": "Assessment Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., PO1, PO2", max_length=20, unique=True
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., CS101, BA203", max_length=50, unique=True
                    ),
                ),
                (
                    "faculty",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "FACULTY"},
                        related_name="taught_courses",
                        to="users.userprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": [
                    "semester__academic_department__academic_year__start_date",
                    "semester__order",
                    "code",
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="e.g., CO1, CO2", max_length=20)),
                ("description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_outcomes",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Outcome",
                "verbose_name_plural": "Course Outcomes",
                "ordering": ["course__code", "code"],
                "unique_together": {("course", "code")},
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Midterm Exam - Unit 1, Assignment 2 - Loops",
                        max_length=200,
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum marks for this assessment",
                        max_digits=5,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date the assessment was conducted/due"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "assessment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="academics.assessmenttype",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="academics.course",
                    ),
                ),
                (
                    "assesses_cos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assessed_by_assessments",
                        to="academics.courseoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["-academic_year__start_date", "course__code", "date"],
                "unique_together": {("name", "course", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="AcademicDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hod",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role__in": ["HOD", "FACULTY"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_department_headed",
                        to="users.userprofile",
                        verbose_name="Head of Department (for this Academic Year)",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_departments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_departments",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Department",
                "verbose_name_plural": "Academic Departments",
                "ordering": ["-academic_year__start_date", "department__name"],
                "unique_together": {("department", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 1st Semester, Spring 2024", max_length=100
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the semester within the academic year",
                    ),
                ),
                (
                    "academic_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicdepartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "ordering": [
                    "-academic_department__academic_year__start_date",
                    "order",
                ],
                "unique_together": {("name", "academic_department")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.semester",
            ),
        ),
        migrations.CreateModel(
            name="CourseOutcomeAttainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attainment_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_attainments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attainments",
                        to="academics.courseoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Outcome Attainment",
                "verbose_name_plural": "Course Outcome Attainments",
                "ordering": [
                    "academic_year__start_date",
                    "course_outcome__course__code",
                    "course_outcome__code",
                ],
                "unique_together": {("course_outcome", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="COPOMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_level",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (0, "None")],
                        default=0,
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_mappings",
                        to="academics.courseoutcome",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_mappings",
                        to="academics.programoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "CO-PO Mapping",
                "verbose_name_plural": "CO-PO Mappings",
                "ordering": ["course_outcome__code", "program_outcome__code"],
                "unique_together": {("course_outcome", "program_outcome")},
            },
        ),
        migrations.CreateModel(
            name="ProgramOutcomeAttainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attainment_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_attainments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attainments",
                        to="academics.programoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Outcome Attainment",
                "verbose_name_plural": "Program Outcome Attainments",
                "ordering": ["academic_year__start_date", "program_outcome__code"],
                "unique_together": {("program_outcome", "academic_year")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("code", "semester")},
        ),
        migrations.CreateModel(
            name="StudentMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marks obtained by the student",
                        max_digits=5,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_marks",
                        to="academics.assessment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Mark",
                "verbose_name_plural": "Student Marks",
                "ordering": ["assessment__date", "student__username"],
                "unique_together": {("assessment", "student")},
            },
        ),
    ]
