# Generated by Django 5.2.3 on 2025-06-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("users", "0003_remove_userprofile_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="course_plan",
                        serialize=False,
                        to="academics.course",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Course Plan for AI (V SEM A & B)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="General overview/introduction for the course plan.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_coordinator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary person responsible for the course plan.",
                        limit_choices_to={"role__in": ["FACULTY", "HOD"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_course_plans",
                        to="users.userprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_course_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other instructors assigned to this course (if any).",
                        related_name="instructed_course_plans",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Plan",
                "verbose_name_plural": "Course Plans",
                "ordering": [
                    "-course__semester__academic_department__academic_year__start_date",
                    "course__code",
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 1, 2, Unit A, Unit B",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "objective_text",
                    models.TextField(
                        help_text="Detailed description of the course objective."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the objective within the Course Plan",
                    ),
                ),
                (
                    "course_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_objectives",
                        to="academics.courseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Objective (Plan)",
                "verbose_name_plural": "Course Objectives (Plan)",
                "ordering": ["order"],
                "unique_together": {("course_plan", "order")},
            },
        ),
        migrations.CreateModel(
            name="CIAComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_name",
                    models.CharField(
                        help_text="e.g., CIA-I Test (10 Marks), CIA-II Assignment (5 Marks)",
                        max_length=200,
                    ),
                ),
                (
                    "units_covered",
                    models.CharField(
                        blank=True,
                        help_text="e.g., UNIT 1 & 2",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the CIA component."
                    ),
                ),
                (
                    "cos_covered",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cia_assessed_by",
                        to="academics.courseoutcome",
                    ),
                ),
                (
                    "course_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cia_components",
                        to="academics.courseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "CIA Component",
                "verbose_name_plural": "CIA Components",
                "ordering": ["order"],
                "unique_together": {("course_plan", "component_name")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(help_text="e.g., I, II, Unit 1", max_length=10),
                ),
                (
                    "unit_details",
                    models.TextField(help_text="Topics covered in this unit/week."),
                ),
                (
                    "week_dates",
                    models.CharField(
                        blank=True,
                        help_text="e.g., JULY 17TH - AUG 10TH",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "pedagogy",
                    models.TextField(
                        blank=True,
                        help_text="Methods used for teaching (e.g., Lecture, Demo, Activity-Based Learning).",
                        null=True,
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        help_text="Textbooks, web links for this unit.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the weekly plan entry."
                    ),
                ),
                (
                    "course_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_lesson_plans",
                        to="academics.courseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Lesson Plan",
                "verbose_name_plural": "Weekly Lesson Plans",
                "ordering": ["order"],
                "unique_together": {("course_plan", "unit_number")},
            },
        ),
    ]
