# Generated by Django 5.2.3 on 2025-06-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_programoutcome'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='e.g., CS101, BA203', max_length=50, unique=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.academicyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.department')),
                ('faculty', models.ManyToManyField(blank=True, limit_choices_to={'role': 'FACULTY'}, related_name='taught_courses', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['academic_year__start_date', 'code'],
                'unique_together': {('code', 'academic_year')},
            },
        ),
    ]
