# Generated by Django 5.2.3 on 2025-06-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_assignment_rubric_rubriccriterion_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="academics.rubric",
            ),
        ),
    ]
