# Generated by Django 5.2.3 on 2025-07-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_department_options_department_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.RemoveField(
            model_name="department",
            name="parent",
        ),
    ]
