# Generated by Django 5.2.3 on 2025-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_assignment_rubric"),
        ("users", "0004_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "STUDENT"},
                related_name="enrolled_courses",
                to="users.userprofile",
            ),
        ),
    ]
