# Generated by Django 5.2.3 on 2025-06-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_courseoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (0, 'None')], default=0)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='academics.courseoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='academics.programoutcome')),
            ],
            options={
                'verbose_name': 'CO-PO Mapping',
                'verbose_name_plural': 'CO-PO Mappings',
                'ordering': ['course_outcome__code', 'program_outcome__code'],
                'unique_together': {('course_outcome', 'program_outcome')},
            },
        ),
    ]
