# Generated by Django 5.2.3 on 2025-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_copomapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Midterm Exam, Assignment, Project, Quiz', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
                'ordering': ['name'],
            },
        ),
    ]
