# Generated by Django 5.2.3 on 2025-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory"),
                    ("PRACTICAL", "Practical"),
                    ("INTEGRATED", "Integrated"),
                ],
                default="THEORY",
                help_text="The type of the course, e.g., Theory or Practical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of credits for the course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(
                blank=True,
                help_text="Knowledge or skills required before taking this course",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_1",
            field=models.BooleanField(default=False, verbose_name="RBT 1 (Remember)"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_2",
            field=models.BooleanField(default=False, verbose_name="RBT 2 (Understand)"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_3",
            field=models.BooleanField(default=False, verbose_name="RBT 3 (Apply)"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_4",
            field=models.BooleanField(default=False, verbose_name="RBT 4 (Analyze)"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_5",
            field=models.BooleanField(default=False, verbose_name="RBT 5 (Evaluate)"),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="rbt_level_6",
            field=models.BooleanField(default=False, verbose_name="RBT 6 (Create)"),
        ),
        migrations.AddField(
            model_name="courseplan",
            name="assessment_ratio",
            field=models.CharField(
                blank=True,
                help_text="The ratio of internal to external assessment marks, e.g., 60:40",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="%Y/%m/%d/"),
        ),
    ]
