# Generated by Django 5.2.3 on 2025-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_department_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="branch",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Commerce", "Commerce"),
                    ("Management", "Management"),
                    ("Arts", "Arts"),
                    ("Science", "Science"),
                    ("Humanities", "Humanities"),
                ],
                max_length=100,
            ),
        ),
    ]
