# Generated by Django 5.2.3 on 2025-07-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_course_course_type_course_credits_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklylessonplan",
            unique_together={("course_plan", "order")},
        ),
    ]
