# Generated by Django 5.2.3 on 2025-06-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_assessmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Midterm Exam - Unit 1, Assignment 2 - Loops', max_length=200)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this assessment', max_digits=5)),
                ('date', models.DateField(help_text='Date the assessment was conducted/due')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.academicyear')),
                ('assesses_cos', models.ManyToManyField(blank=True, related_name='assessed_by_assessments', to='academics.courseoutcome')),
                ('assessment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='academics.assessmenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.course')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-academic_year__start_date', 'course__code', 'date'],
                'unique_together': {('name', 'course', 'academic_year')},
            },
        ),
    ]
