# Generated by Django 5.2.3 on 2025-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_weeklylessonplan_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseplan",
            name="description",
        ),
        migrations.AddField(
            model_name="courseplan",
            name="classes_per_week",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Number of classes scheduled per week for this course.",
            ),
        ),
        migrations.AddField(
            model_name="courseplan",
            name="total_hours_allotted",
            field=models.PositiveIntegerField(
                default=60, help_text="Total hours allotted for the entire course."
            ),
        ),
    ]
