# Generated by Django 5.2.3 on 2025-06-21 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcomeAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_attainments', to='academics.academicyear')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='academics.courseoutcome')),
            ],
            options={
                'verbose_name': 'Course Outcome Attainment',
                'verbose_name_plural': 'Course Outcome Attainments',
                'ordering': ['academic_year__start_date', 'course_outcome__course__code', 'course_outcome__code'],
                'unique_together': {('course_outcome', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcomeAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attainments', to='academics.academicyear')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainments', to='academics.programoutcome')),
            ],
            options={
                'verbose_name': 'Program Outcome Attainment',
                'verbose_name_plural': 'Program Outcome Attainments',
                'ordering': ['academic_year__start_date', 'program_outcome__code'],
                'unique_together': {('program_outcome', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by the student', max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='academics.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'ordering': ['assessment__date', 'student__username'],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
