# Generated by Django 5.2.3 on 2025-06-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_courseoutcomeattainment_programoutcomeattainment_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, limit_choices_to={'role__in': ['HOD', 'FACULTY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='users.userprofile', verbose_name='Head of Department'),
        ),
    ]
