# Generated by Django 5.2.3 on 2025-07-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_remove_courseplan_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklylessonplan",
            name="week_dates",
        ),
        migrations.AddField(
            model_name="weeklylessonplan",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date for the weekly plan", null=True
            ),
        ),
        migrations.AddField(
            model_name="weeklylessonplan",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Start date for the weekly plan", null=True
            ),
        ),
    ]
