# Generated by Django 5.2.3 on 2025-07-03 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_remove_weeklylessonplan_week_dates_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programoutcome",
            options={
                "ordering": ["department__name", "code"],
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
            },
        ),
        migrations.AddField(
            model_name="programoutcome",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_outcomes",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="programoutcome",
            name="code",
            field=models.CharField(help_text="e.g., PO1, PO2", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="programoutcome",
            unique_together={("department", "code")},
        ),
    ]
