# Generated by Django 5.2.3 on 2025-07-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_alter_programoutcome_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programoutcome",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_outcomes",
                to="academics.department",
            ),
            preserve_default=False,
        ),
    ]
