# Generated by Django 5.2.3 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_ciacomponent_evaluation_rubric_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assesses_cos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the Course Outcomes that this assignment assesses.",
                related_name="assessed_by_assignments",
                to="academics.courseoutcome",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="max_marks",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="The maximum marks for this assignment.",
                max_digits=6,
            ),
        ),
    ]
