# Generated by Django 5.2.3 on 2025-07-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0013_assignment_assesses_cos_assignment_max_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="max_marks",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Maximum marks for this assessment",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_marks",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="The maximum marks for this assignment.",
                max_digits=6,
            ),
        ),
    ]
