# Generated by Django 5.2.3 on 2025-07-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_assessment_max_marks_and_more'),  # ✅ Fixed
        ("users", "0004_userprofile_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AlterModelOptions(
            name="courseoutcome",
            options={
                "ordering": ["code"],
                "verbose_name": "Course Outcome",
                "verbose_name_plural": "Course Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="courseoutcomeattainment",
            options={
                "ordering": ["academic_year__start_date", "course_outcome__code"],
                "verbose_name": "Course Outcome Attainment",
                "verbose_name_plural": "Course Outcome Attainments",
            },
        ),
        migrations.AlterModelOptions(
            name="courseplan",
            options={
                "ordering": ["title"],
                "verbose_name": "Course Plan",
                "verbose_name_plural": "Course Plans",
            },
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseplan",
            name="course",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="e.g., BCA, BBA", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.department",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                help_text="e.g., Bachelor of Computer Applications", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="marks_obtained",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Artificial Intelligence", max_length=200
                    ),
                ),
                ("code", models.CharField(help_text="e.g., CA-C21T", max_length=50)),
                ("credits", models.PositiveIntegerField(default=4)),
                ("prerequisites", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.course",
                    ),
                ),
                (
                    "faculty",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taught_subjects",
                        to="users.userprofile",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("code", "semester")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="courseoutcome",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_outcomes",
                to="academics.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseplan",
            name="subject",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="course_plan",
                serialize=False,
                to="academics.subject",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="courseoutcome",
            unique_together={("subject", "code")},
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="courseoutcome",
            name="course",
        ),
    ]
