# Generated by Django 5.2.3 on 2025-07-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_assessment_max_marks_and_more'),  # ✅ Fixed
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={},
        ),
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="copomapping",
            options={
                "verbose_name": "CO-PO Mapping",
                "verbose_name_plural": "CO-PO Mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="courseoutcome",
            options={
                "verbose_name": "Course Outcome",
                "verbose_name_plural": "Course Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="courseoutcomeattainment",
            options={
                "verbose_name": "Course Outcome Attainment",
                "verbose_name_plural": "Course Outcome Attainments",
            },
        ),
        migrations.AlterModelOptions(
            name="courseplan",
            options={
                "verbose_name": "Course Plan",
                "verbose_name_plural": "Course Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterModelOptions(
            name="programoutcome",
            options={
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="programoutcomeattainment",
            options={
                "verbose_name": "Program Outcome Attainment",
                "verbose_name_plural": "Program Outcome Attainments",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={},
        ),
        migrations.AlterModelOptions(
            name="studentmark",
            options={
                "verbose_name": "Student Mark",
                "verbose_name_plural": "Student Marks",
            },
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="courseoutcome",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_outcomes",
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="semester",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="semester",
            name="academic_department",
        ),
    ]
