# Generated by Django 5.2.3 on 2025-07-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_assessment_max_marks_and_more'),  # ✅ Fixed
        ("users", "0005_remove_userprofile_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseplan",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="subject",
        ),
        migrations.AlterModelOptions(
            name="academicyear",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
            },
        ),
        migrations.AlterModelOptions(
            name="assessment",
            options={
                "ordering": ["-academic_year__start_date", "course__code", "date"],
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="copomapping",
            options={
                "ordering": ["course_outcome__code", "program_outcome__code"],
                "verbose_name": "CO-PO Mapping",
                "verbose_name_plural": "CO-PO Mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": [
                    "semester__academic_department__academic_year__start_date",
                    "semester__order",
                    "code",
                ],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="courseoutcome",
            options={
                "ordering": ["course__code", "code"],
                "verbose_name": "Course Outcome",
                "verbose_name_plural": "Course Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="courseoutcomeattainment",
            options={
                "ordering": [
                    "academic_year__start_date",
                    "course_outcome__course__code",
                    "course_outcome__code",
                ],
                "verbose_name": "Course Outcome Attainment",
                "verbose_name_plural": "Course Outcome Attainments",
            },
        ),
        migrations.AlterModelOptions(
            name="courseplan",
            options={
                "ordering": [
                    "-course__semester__academic_department__academic_year__start_date",
                    "course__code",
                ],
                "verbose_name": "Course Plan",
                "verbose_name_plural": "Course Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="programoutcome",
            options={
                "ordering": ["department__name", "code"],
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="programoutcomeattainment",
            options={
                "ordering": ["academic_year__start_date", "program_outcome__code"],
                "verbose_name": "Program Outcome Attainment",
                "verbose_name_plural": "Program Outcome Attainments",
            },
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": [
                    "-academic_department__academic_year__start_date",
                    "order",
                ],
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
            },
        ),
        migrations.AlterModelOptions(
            name="studentmark",
            options={
                "ordering": ["assessment__date", "student__username"],
                "verbose_name": "Student Mark",
                "verbose_name_plural": "Student Marks",
            },
        ),
        migrations.AlterUniqueTogether(
            name="courseoutcome",
            unique_together={("course", "code")},
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory"),
                    ("PRACTICAL", "Practical"),
                    ("INTEGRATED", "Integrated"),
                ],
                default="THEORY",
                help_text="The type of the course, e.g., Theory or Practical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of credits for the course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "FACULTY"},
                related_name="taught_courses",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(
                blank=True,
                help_text="Knowledge or skills required before taking this course",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.semester",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "STUDENT"},
                related_name="enrolled_courses",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_outcomes",
                to="academics.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseplan",
            name="course",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="course_plan",
                serialize=False,
                to="academics.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="semester",
            name="academic_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to="academics.academicdepartment",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="e.g., CS101, BA203", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                help_text="e.g., 1st Semester, Spring 2024", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order of the semester within the academic year"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("code", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("name", "academic_department")},
        ),
        migrations.RemoveField(
            model_name="courseoutcome",
            name="subject",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
